site_name: My Notes

repo_url: https://github.com/pratzohol/MindML
repo_name: pratzohol/MindML

theme:
    name: material
    icon:
      repo: fontawesome/brands/github
    palette:
      # Light mode
      - media: "(prefers-color-scheme: light)"
        scheme: default
        primary: indigo
        accent: purple
        toggle:
          icon: material/weather-sunny
          name: Switch to dark mode
      # Dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: indigo
        accent: purple
        toggle:
          icon: material/weather-night
          name: Switch to light mode          
    features:
      - navigation.tracking
      - navigation.tabs
      - navigation.tabs.sticky
      - navigation.sections
      - navigation.path
      - navigation.indexes
      - toc.follow
      - navigation.top
      - search.suggest
      - search.share
      - navigation.footer

# Extensions
markdown_extensions:
  - footnotes
  - tables
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.magiclink
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - toc:
      permalink: true


plugins:
  - search
  - roamlinks
  - tags:
      tags_compare: !!python/name:material.plugins.tags.casefold


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://unpkg.com/mermaid/dist/mermaid.min.js 


extra:
  social:
      - icon: fontawesome/brands/twitter
        link: https://twitter.com/pratzohol/
        name: Twitter
      - icon: fontawesome/brands/github
        link: https://github.com/pratzohol/
        name: GitHub
      - icon: fontawesome/brands/linkedin
        link: https://www.linkedin.com/in/pratzohol/
        name: LinkedIn
      - icon: fontawesome/brands/instragram
        link: https://www.instagram.com/pratzohol/
        name: Instagram
      - icon: fontawesome/solid/paper-plane
        link: mailto:IITDprateekmishra@gmail.com
        name: Email

#   consent:
#     title: Cookie consent
#     description: >- 
#       We use cookies to recognize your repeated visits and preferences, as well
#       as to measure the effectiveness of my documentation and whether users
#       find what they're searching for. With your consent, you're helping me to
#       make my documentation better.
#     cookies:
#       analytics: 
#     actions:
#       - accept
#       - manage