name: ci
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v2
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install \
                mkdocs-material \
                mkdocs-awesome-pages-plugin \
                mkdocs-git-revision-date-localized-plugin \
                mkdocs-git-committers-plugin-2 \
                mkdocs-git-authors-plugin \
                pillow cairosvg \
                mkdocs-glightbox \
                
                mkdocs-minify-plugin \
                mkdocs-mermaid2-plugin \
                mkdocs-macros-plugin \
      - run: mkdocs gh-deploy --force
